use customer_behaviour

select * from customer_behaviour_cleaned
limit 10;

# what is the total revenue generated by male and female customer
select gender, sum(purchse_amount) as revenue from customer_behaviour_cleaned
group by gender;

# which customers used a discount but still spent more than average
select customer_id, purchse_amount from customer_behaviour_cleaned
where discount_applied = 'Yes' and purchse_amount >= 
(
select avg(purchse_amount) from customer_behaviour_cleaned
);

# which are the top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2) as average_rating from customer_behaviour_cleaned
group by item_purchased
order by avg(review_rating) desc
limit 5;

# compare the average purchase amouns between standard and express shipping
select shipping_type, round(avg(purchse_amount), 2) as popular_shipping from customer_behaviour_cleaned
where shipping_type in ('Standard', 'express')
group by shipping_type;

# Do subscribed customers spend more ??
select subscription_status, count(customer_id) as total_customers, round(avg(purchse_amount),2) as average_spent, round(sum(purchse_amount),2) as total_revenue from customer_behaviour_cleaned
group by subscription_status
order by total_revenue, average_spent;

# which 5 products have the highest percentage of purchases with discount applied
select item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate from customer_behaviour_cleaned
group by item_purchased
order by discount_rate desc
limit 5;

#segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases, 
case 
	when previous_purchases =1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer_behaviour_cleaned
)
select customer_segment, count(*) as number_of_customers from customer_type
group by customer_segment;

# what are the most 3 purchased items from each category
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_behaviour_cleaned
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts

# Are customers who are repeat buyers also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers from customer_behaviour_cleaned
where previous_purchases >5
group by subscription_status;

# what is the revenue contribution of each age group
select age_group, sum(purchse_amount) as total_revenue from customer_behaviour_cleaned
group by age_group
order by total_revenue desc;